production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev

test:
  adapter: postgresql
  encoding: utf8
  database: kn_test
  pool: 5
  username: kn_user
  password: 123456

development:
  adapter: postgresql
  encoding: utf8
  database: kn_development
  pool: 5
  username: kn_user
  password: 123456
